diff --git a/Dockerfile b/Dockerfile
index 2dc94cd..03ae213 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,10 +1,27 @@
-FROM maven:3.6.3-jdk-11
+FROM bellsoft/liberica-openjdk-alpine:21
 
 WORKDIR /app
 
-RUN apt-get install -y curl \
-  && curl -sL https://deb.nodesource.com/setup_12.x | bash - \
-  && curl https://cli-assets.heroku.com/install-ubuntu.sh | bash - \
-  && apt-get install -y nodejs
+ENV NODE_VERSION=16.20.0
+RUN apk add curl
+RUN apk add bash
+RUN apk add maven
+RUN apk add --no-cache libstdc++
+RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
+ENV NVM_DIR=/root/.nvm
+RUN . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION}
+RUN . "$NVM_DIR/nvm.sh" && nvm use v${NODE_VERSION}
+RUN . "$NVM_DIR/nvm.sh" && nvm alias default v${NODE_VERSION}
+ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"
 
-CMD ["/bin/bash"]
+RUN node --version
+RUN npm --version
+
+COPY src /home/app/src
+COPY frontend /home/app/frontend
+COPY lombok.config /home/app
+COPY pom.xml /home/app
+
+RUN mvn -B -Pproduction -Ph2 -DskipTests -f /home/app/pom.xml clean package
+
+ENTRYPOINT ["java","-jar","/home/app/target/team03-1.0.0.jar"]
\ No newline at end of file
