diff --git a/Dockerfile b/Dockerfile
index 3a37c4c..9e794d7 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -9,19 +9,16 @@
 
 ARG JRE=adoptopenjdk/openjdk11:jre-11.0.9_11-alpine
 
-FROM maven:3.6.3-jdk-11-openj9 as mavenbuild
+FROM brunoe/maven:3.6.3-jdk-11-openj9 as mavenbuild
 # A Variable to indicate if the build is in CI Server
 ARG CI
+
 # Github Credentials
 ARG GITHUBLOGIN
 ENV GITHUBLOGIN=$GITHUBLOGIN
 ARG GITHUBPASSWORD
 ENV GITHUBPASSWORD=$GITHUBPASSWORD
-# Bintray Credentials
-ARG BINTRAY_USERNAME
-ENV BINTRAY_USERNAME=$BINTRAY_USERNAME
-ARG BINTRAY_API_KEY
-ENV BINTRAY_API_KEY=$BINTRAY_API_KEY
+
 # Dockerhub Credentials
 ARG DOCKER_USERNAME
 ENV DOCKER_USERNAME=$DOCKER_USERNAME
@@ -31,7 +28,7 @@ ENV DOCKER_PASSWORD=$DOCKER_PASSWORD
 WORKDIR /build
 COPY . /build
 
-ENV MAVEN_PARAM="--settings /build/ci-settings.xml -B -e -T 1C"
+ENV MAVEN_PARAM="--settings /build/.github/ci-settings.xml -B -e -T 1C"
 
 RUN --mount=type=cache,target=/root/.m2 mvn $MAVEN_PARAM clean package
 
