"""Run OpenHands investigator on ONE stage, live, with the AWQ compactor as
LLMSummarizingCondenser. No batch, no pool — just one repo and human attention.

Usage:  python3 oh_one_live.py <slug>
        slug is the per_repo_iter dirname (e.g. 'Syzmel_TASKHD__J11toJ21')
"""
import os, sys, json, subprocess, tarfile, io, tempfile, re, time

os.environ.setdefault('OPENHANDS_SUPPRESS_BANNER', '1')
for ln in open('/home/vmihaylov/java_8_11_17_to_java_21/.env'):
    ln = ln.strip()
    if not ln or ln.startswith('#') or '=' not in ln: continue
    k, v = ln.split('=', 1); v = v.strip().strip('"').strip("'")
    os.environ.setdefault(k, v)

if len(sys.argv) != 2:
    print(__doc__); sys.exit(2)
slug = sys.argv[1]
# Default: read FAIL observations from current_attempt (current Qwen partial-info baseline).
# Override via OH_TRAJ_DIR for ad-hoc replays of older attempts.
TRAJ_DIR = os.environ.get('OH_TRAJ_DIR',
                          '/home/vmihaylov/java_8_11_17_to_java_21/current_attempt/per_repo_iter')
TRAJ = f'{TRAJ_DIR}/{slug}/trajectory.json'
# Findings persist under current_attempt/investigator_findings/<slug>.json.
FINDINGS_DIR = '/home/vmihaylov/java_8_11_17_to_java_21/current_attempt/investigator_findings'
os.makedirs(FINDINGS_DIR, exist_ok=True)
t = json.load(open(TRAJ))
stage = t['stage']
obs = t['history'][-1]['observation'][:3000]
print(f'=== stage: {stage["repo"]} {stage["jv_from"]}→{stage["jv_to"]} sha={stage["sha_from"][:10]}')
print(f'=== verdict was: {t.get("final_verdict")}')
print(f'=== failure observation (first 600 chars):\n{obs[:600]}\n', flush=True)

# Fetch source
workdir = tempfile.mkdtemp(prefix=f'oh_live_{slug[:20]}_')
git_dir = f'{os.environ["MIRROR_CACHE_DIR"]}/{stage["repo"]}.git'
print(f'=== fetching {stage["sha_from"][:10]} → {workdir}', flush=True)
r = subprocess.run(['git', 'archive', '--format=tar', stage['sha_from']],
                   cwd=git_dir, capture_output=True, timeout=60)
if r.returncode != 0:
    print(f'FETCH_FAIL rc={r.returncode}: {r.stderr.decode()[:300]}'); sys.exit(3)
with tarfile.open(fileobj=io.BytesIO(r.stdout)) as tf:
    tf.extractall(workdir)
print(f'=== source extracted, {sum(1 for _ in os.walk(workdir))} dirs\n', flush=True)

# Brief — same shape as the throughput probe
brief = f'''You are an investigator subagent. Read source — do not propose fixes or mutate the build.

A Spring/Maven project at jv_from={stage["jv_from"]} failed migrating to jv_to={stage["jv_to"]} with this observation:

{obs[:2500]}

Tasks:
1. Identify the file(s) and exact lines the failure cites
2. Open them and report the structural cause in 1–3 sentences (what's there, why this fails post-recipe)
3. Note any pom-level pins (plugin versions, properties) that are relevant

Emit ONE final JSON object (the last thing you say) with keys:
  slug, root_cause_summary (2–3 sentences), cited_files (list of paths),
  relevant_pom_pins (list of {{key, value}}), fix_hint (one-liner)
slug = "{slug}"
'''

from openhands.sdk import LLM, Agent, Conversation, LocalWorkspace
from openhands.tools.preset.default import get_default_tools
from openhands.sdk.event import MessageEvent
from openhands.sdk.context.condenser import LLMSummarizingCondenser
from pydantic import SecretStr
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from oh_event_sink import make_callback as oh_make_sink_callback

# Main LLM = Qwen FP8 (proposer)
llm = LLM(
    model=f'openai/{os.environ["PROPOSER_MODEL"]}',
    base_url=os.environ['PROPOSER_BASE_URL'],
    api_key=SecretStr(os.environ['PROPOSER_API_KEY']),
    usage_id=f'oh_live_{slug[:40]}',
    max_output_tokens=2048,
    temperature=0.0,
    native_tool_calling=True,
)
# Compactor LLM = Qwen AWQ on separate vLLM (per .env COMPACTOR_*)
compactor_llm = LLM(
    model=f'openai/{os.environ["OPENHANDS_CONTEXT_COMPACTOR_MODEL"]}',
    base_url=os.environ['OPENHANDS_CONTEXT_COMPACTOR_BASE_URL'],
    api_key=SecretStr(os.environ['OPENHANDS_CONTEXT_COMPACTOR_API_KEY']),
    usage_id=f'oh_live_condenser_{slug[:40]}',
    max_output_tokens=4096,
    temperature=0.0,
    native_tool_calling=False,
)
condenser = LLMSummarizingCondenser(
    llm=compactor_llm,
    max_size=40,    # condense when events exceed this
    keep_first=2,   # always retain the brief + first response
)
print(f'=== LLM: {os.environ["PROPOSER_MODEL"]} via {os.environ["PROPOSER_BASE_URL"]}')
print(f'=== Condenser: {os.environ["OPENHANDS_CONTEXT_COMPACTOR_MODEL"]} via {os.environ["OPENHANDS_CONTEXT_COMPACTOR_BASE_URL"]}  (max_size=40)\n', flush=True)

agent = Agent(llm=llm,
              tools=get_default_tools(enable_browser=False),
              condenser=condenser)
# Pre-build the sink so we can pass it as a callback. conv_id is generated by
# Conversation; we use the slug for now and patch the conv_id after construction.
import uuid as _uuid
_conv_id = _uuid.uuid4()
_sink_cb = oh_make_sink_callback(_conv_id, slug=slug)
conv = Conversation(agent=agent,
                    workspace=LocalWorkspace(working_dir=workdir),
                    conversation_id=_conv_id,
                    callbacks=[_sink_cb],
                    max_iteration_per_run=25)
print(f'=== OH events stream: /var/log/observe/openhands.jsonl (conv_id={_conv_id})\n', flush=True)
# Default visualizer streams events live to stdout.
t0 = time.time()
conv.send_message(brief)
conv.run()
wall = round(time.time() - t0, 1)

print(f'\n=== wall: {wall}s, {len(conv.state.events)} events')

# Try to extract a final JSON
finding = None; last_agent_text = None
for ev in conv.state.events:
    if isinstance(ev, MessageEvent) and ev.source == 'agent':
        for c in ev.llm_message.content:
            txt = getattr(c, 'text', '') or ''
            if txt:
                last_agent_text = txt
                m = re.search(r'\{[\s\S]*\}', txt)
                if m:
                    try: finding = json.loads(m.group(0))
                    except Exception: pass

print('\n=== final agent text (last MessageEvent):')
print((last_agent_text or '(none)')[-1500:])
print('\n=== parsed finding:')
if finding:
    print(json.dumps(finding, indent=2))
    with open(f'{FINDINGS_DIR}/{slug}.json', 'w') as f:
        json.dump({'wall_s': wall, 'events': len(conv.state.events), 'finding': finding}, f, indent=2)
    print(f'\npersisted: {FINDINGS_DIR}/{slug}.json')
else:
    print('(no JSON parsed)')
print(f'\nworkdir kept for inspection: {workdir}')
