diff --git a/Dockerfile b/Dockerfile
index 131f7e9..3047838 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,4 +1,4 @@
-FROM eclipse-temurin:17-jdk
+FROM eclipse-temurin:21-jdk-alpine
 
 # Directorio de trabajo dentro del contenedor
 WORKDIR /app
