diff --git a/Dockerfile b/Dockerfile
index 5f59710..e33e565 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,4 +1,4 @@
-FROM maven:3.9.11-eclipse-temurin-17
+FROM maven:3.9.11-eclipse-temurin-21
 WORKDIR /app
 COPY pom.xml .
 COPY src ./src
