diff --git a/Dockerfile b/Dockerfile
index 5672565..445acec 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,6 +1,6 @@
-FROM openjdk:15-jdk-alpine
+FROM openjdk:17-jdk-alpine
 VOLUME /tmp
-EXPOSE 8099
+EXPOSE 9080
 RUN mkdir -p /app/
 RUN mkdir -p /app/logs/
 ADD target/spring-boot-jsonb-0.0.1-SNAPSHOT.jar /app/app.jar
