diff --git a/Dockerfile b/Dockerfile
index ab2ad55..8de8b5f 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -4,11 +4,19 @@ LABEL authors="Thai_Binh_Nguyen"
 # Create app directory
 WORKDIR /app
 
+# Copy healthcheck script
+COPY healthcheck.sh /app/healthcheck.sh
+RUN chmod +x /app/healthcheck.sh
+
 # Copy JAR into container
-COPY target/webscraper-0.0.1-SNAPSHOT.jar app.jar
+COPY target/quizme-0.0.1-SNAPSHOT.jar app.jar
 
 # Create a folder for SQLite DB (inside container, will be mounted outside)
 RUN mkdir -p /data
 
+# Healthcheck
+HEALTHCHECK --interval=30s --timeout=5s --start-period=15s --retries=3 \
+  CMD /app/healthcheck.sh
+
 ENTRYPOINT ["java", "-jar", "app.jar"]
 
