diff --git a/Dockerfile b/Dockerfile
index 1e6601c..dee04fe 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -13,7 +13,7 @@ FROM openjdk:17.0.1-slim
 EXPOSE 8080
 RUN mkdir /app 
 WORKDIR /app
-ENTRYPOINT ["java","--add-opens","java.base/sun.nio.ch=ALL-UNNAMED","--add-opens","java.base/java.io=ALL-UNNAMED","-Dfile.encoding=UTF-8","org.springframework.boot.loader.JarLauncher"]
+ENTRYPOINT ["java","--add-opens","java.base/sun.nio.ch=ALL-UNNAMED","--add-opens","java.base/java.io=ALL-UNNAMED","-Dfile.encoding=UTF-8","org.springframework.boot.loader.launch.JarLauncher"]
 COPY --from=builder /project/build/libs/spring-boot-loader    /app
 COPY --from=builder /project/build/libs/dependencies          /app
 COPY --from=builder /project/build/libs/snapshot-dependencies /app
