diff --git a/Dockerfile b/Dockerfile
index 4c89c69..6d33883 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,7 +1,29 @@
-FROM openjdk:11
+# Stage 1: Build the project
+
+FROM openjdk:21-slim AS MAVEN_BUILD
+
+# Install Maven
+RUN apt-get update && apt-get install -y maven
+
 # Tomcat creates a working dir at /tmp by default. Might be optional
 VOLUME /tmp
-ARG JAR_FILE
-COPY target/*.jar app.jar
+COPY pom.xml /build/
+COPY src /build/src/
+WORKDIR /build/
+RUN mvn package -DskipTests=true
+RUN ls /build/target
+
+# Stage 2: prepare launch environment
+FROM openjdk:21-slim
+# Running with user privileges helts to migate some risks: This is currently disabled bacause
+# The application did not have enough privileges to save images to disk
+RUN addgroup --system spring && adduser --system --ingroup spring spring
+USER spring:spring
+WORKDIR /app
+COPY --from=MAVEN_BUILD /build/target/*.jar /app/
+RUN ls /app/
+
 # To reduce startup time: adding /dev/urandom as a source of entropy
-ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
+ENV SERVER_PORT=8000
+ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app/hilfling-0.0.1-SNAPSHOT.jar"]
+EXPOSE 8000
\ No newline at end of file
