diff --git a/Dockerfile b/Dockerfile
index 48c2be0..6686aca 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -3,7 +3,7 @@
 ##
 ## Build
 ##
-FROM --platform=$BUILDPLATFORM golang:1.24-bullseye AS build
+FROM --platform=$BUILDPLATFORM golang:1.25-trixie AS build
 
 ARG TARGETOS
 ARG TARGETARCH
@@ -38,7 +38,7 @@ RUN make licenses-report
 ##
 ## Runtime
 ##
-FROM azul/zulu-openjdk-debian:23
+FROM azul/zulu-openjdk-debian:25
 
 ARG VERSION=unknown
 ARG REVISION=unknown
@@ -54,8 +54,8 @@ RUN apt-get -qq update && \
     rm -rf /var/lib/apt/lists/*
 
 # Install Maven
-ENV MAVEN_VERSION=3.9.6
-ENV MAVEN_BASE_URL=https://dlcdn.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries
+ENV MAVEN_VERSION=3.9.11
+ENV MAVEN_BASE_URL=https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries
 ENV MAVEN_FILENAME=apache-maven-${MAVEN_VERSION}-bin.tar.gz
 RUN apt-get update && apt-get install -y wget tar && \
     wget ${MAVEN_BASE_URL}/${MAVEN_FILENAME} -O /tmp/${MAVEN_FILENAME} && \
@@ -92,8 +92,8 @@ USER $USER_UID
 RUN mkdir -p /tmp/.java/.systemPrefs /tmp/.java/.userPrefs && \
     chmod -R 755 /tmp/.java
 
-ENV JAVA_OPTS="-Djava.util.prefs.systemRoot=/tmp/.java -Djava.util.prefs.userRoot=/tmp/.java/.userPrefs"
-ENV MAVEN_OPTS="-Djava.util.prefs.systemRoot=/tmp/.java -Djava.util.prefs.userRoot=/tmp/.java/.userPrefs"
+ENV JAVA_OPTS="-Djava.util.prefs.systemRoot=/tmp/.java -Djava.util.prefs.userRoot=/tmp/.java/.userPrefs -Dsteadybit.agent.disable-jvm-attachment"
+ENV MAVEN_OPTS="-Djava.util.prefs.systemRoot=/tmp/.java -Djava.util.prefs.userRoot=/tmp/.java/.userPrefs -Dsteadybit.agent.disable-jvm-attachment"
 
 # Run a simple test to pre-load all required dependencies
 RUN cd /gatling-maven-scaffold && \
