diff --git a/Dockerfile b/Dockerfile
index 6334423..24a9fbf 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -9,4 +9,4 @@ COPY --from=builder dependencies/ ./
 COPY --from=builder snapshot-dependencies/ ./
 COPY --from=builder spring-boot-loader/ ./
 COPY --from=builder application/ ./
-ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher"]
\ No newline at end of file
+ENTRYPOINT ["java", "org.springframework.boot.loader.launch.JarLauncher"]
\ No newline at end of file
