diff --git a/Dockerfile_full b/Dockerfile_full
index d88e42f..fd88230 100644
--- a/Dockerfile_full
+++ b/Dockerfile_full
@@ -18,4 +18,4 @@ COPY --from=maven_build dependencies/ ./
 COPY --from=maven_build snapshot-dependencies/ ./
 COPY --from=maven_build spring-boot-loader/ ./
 COPY --from=maven_build application/ ./
-ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher"]
\ No newline at end of file
+ENTRYPOINT ["java", "org.springframework.boot.loader.launch.JarLauncher"]
\ No newline at end of file
