diff --git a/Dockerfile b/Dockerfile
index 9025f97..1e0049b 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,4 +1,4 @@
-FROM folioci/alpine-jre-openjdk17:latest
+FROM folioci/alpine-jre-openjdk21:latest
 
 # Copy your fat jar to the container provide the actual name for your fat jar file for example mod-notes-fat.jar
 ENV APP_FILE mod-circulation-bff.jar
@@ -8,4 +8,4 @@ ARG JAR_FILE=./target/*.jar
 COPY ${JAR_FILE} ${JAVA_APP_DIR}/${APP_FILE}
 
 # Expose this port locally in the container.
-EXPOSE 8081
\ No newline at end of file
+EXPOSE 8081
