diff --git a/Dockerfile b/Dockerfile
index 255b62c..d3a064f 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,6 +1,6 @@
-FROM eclipse-temurin:17
+FROM amazoncorretto:21.0.4-alpine3.18
 WORKDIR app
 ARG JAR_FILE=target/*.jar
 COPY ${JAR_FILE} spring-boot-boilerplate.jar
 EXPOSE 8080
-ENTRYPOINT ["java","-jar","spring-boot-boilerplate.jar"]
\ No newline at end of file
+ENTRYPOINT ["java","-jar","spring-boot-boilerplate.jar"]
