diff --git a/Dockerfile b/Dockerfile
index 17746fc..df15541 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,28 +1,13 @@
-# Stage 1: Build the application
-FROM ubuntu:latest AS build
-
-# Install dependencies (OpenJDK 21 and Maven)
-RUN apt-get update && \
-    apt-get install -y openjdk-21-jdk maven && \
-    rm -rf /var/lib/apt/lists/*
-
-# Set the working directory
+# Stage 1: Build the application with Maven
+FROM jelastic/maven:3.9.5-openjdk-21 AS builder
 WORKDIR /app
-
-# Copy the JAR file and necessary folders
-COPY ./target /app/target
+COPY pom.xml .
+COPY src ./src
+RUN mvn clean package -DskipTests
 
 # Stage 2: Create the final image
-FROM adoptopenjdk/openjdk21:alpine-jre
-
-# Set the working directory
+FROM openjdk:21-jdk-slim AS runner
 WORKDIR /app
-
-# Copy the JAR file and necessary folders from the build stage
-COPY --from=build /app/target /app/target
-
-# Expose the port
+COPY --from=builder /app/target/mavenproject1-1.0-SNAPSHOT.jar mavenproject1-1.0-SNAPSHOT.jar
 EXPOSE 8080
-
-# Run the application
-CMD ["java", "-jar", "/app/target/mavenproject1-1.0-SNAPSHOT.jar"]
+ENTRYPOINT ["java", "-jar", "mavenproject1-1.0-SNAPSHOT.jar"]
\ No newline at end of file
