diff --git a/Makefile b/Makefile
index 30d5ae9..fd7be48 100644
--- a/Makefile
+++ b/Makefile
@@ -1,38 +1,58 @@
-dev-backend:
-	mvn compile quarkus:dev
+dev-api:
+	cd api && mvn compile quarkus:dev
 
-dev-backend-only:
-	mvn compile quarkus:dev -Pbackend-only
+test-api:
+	cd api && mvn clean test -DskipITs
 
-test-backend-only:
-	mvn clean test -Pbackend-only
+start-api:
+	java -jar api/target/quarkus-app/quarkus-run.jar
 
-dev-web:
-	cd src/main/frontend && yarn && yarn dev
+it-api:
+	cd api && mvn clean verify
+
+build-api:
+	cd api && mvn clean install -DskipTests
+
+docker-build-api:
+	cd api && docker build -f src/main/docker/Dockerfile.multistage -t quay.io/quarkus/code-quarkus-api .
+
+build-lib:
+	cd library && yarn && yarn build
+
+test-lib:
+	cd library && yarn test
+
+tag-lib:
+	cd library && yarn run tag
+
+link-lib:
+	cd library && yarn && yarn build && yarn run link;
+	cd frontend && yarn run link-library;
+
+unlink-lib:
+	cd frontend && yarn && yarn run unlink-library;
+	cd library && yarn && yarn run unlink;
 
 dev:
-	make -j2 dev-backend-only dev-web
+	cd api && mvn quarkus:dev
+
+test-frontend:
+	cd frontend && yarn && yarn test
 
-test-web:
-	cd src/main/frontend && yarn && yarn test:i
+build-frontend:
+	cd frontend && yarn && yarn build
 
-update-web-snapshots:
-	cd src/main/frontend && yarn && yarn test -u
+start-frontend:
+	cd frontend && yarn run run
 
-debug:
-	mvn compile quarkus:dev -Ddebug -Dsuspend
+docker-build-frontend:
+	cd frontend && docker build -f docker/Dockerfile.multistage -t quay.io/quarkus/code-quarkus-frontend .
 
-clean:
-	mvn clean
+compose:
+	docker-compose up
 
-clean-backend-only:
-	mvn clean -Pbackend-only
+deploy-openshift:
+	cd openshift && ./deploy.sh;
 
-native:
-	mvn package -Pnative -DskipTests
 
-ext-add:
-	mvn quarkus:add-extension -Dextensions="$(ID)"
 
-ext-list:
-	mvn quarkus:list-extensions
