diff --git a/Dockerfile b/Dockerfile
index a894ab2..7768d1d 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,9 +1,4 @@
 FROM mcr.microsoft.com/java/jre-headless:11-zulu-ubuntu
 
-ENV POSTGRES_URL=
-ENV POSTGRES_USER=
-ENV POSTGRES_PASS=
-
 COPY ./target/*.jar /app.jar
 ENTRYPOINT ["java","-jar","/app.jar"]
-# ENTRYPOINT ["java", "-Dspring.profiles.active=h2", "-jar", "/app.jar"]
\ No newline at end of file
