diff --git a/Dockerfile b/Dockerfile
index c40cb32..4d55168 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -2,8 +2,7 @@ FROM openjdk:17-oracle
 
 COPY target/MyWorkouts-1.jar /usr/app/
 WORKDIR /usr/app
-RUN mkdir -p logs/ export/ tokens/ img/ img/exercises
-COPY tokens/StoredCredential tokens/
+RUN mkdir -p logs/ export/ img/ img/exercises
 WORKDIR /usr/app
 EXPOSE 8081
 
