diff --git a/Dockerfile b/Dockerfile
index c45f908c..210b3dab 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,16 +1,9 @@
-FROM adorsys/openjdk-jre-base:8-minideb
+FROM adorsys/java:11
 
-RUN apt-get update && apt-get install -y curl
+WORKDIR /tmp/keycloak-config-cli
+VOLUME /tmp/keycloak-config-cli/configs
 
-ENV JAVA_OPTS ""
+COPY ./config-cli/target/config-cli.jar ./keycloak-config-cli.jar
+COPY ./docker/root/ /
 
-RUN mkdir -p /opt/keycloak-config-cli/configs
-
-WORKDIR /opt/keycloak-config-cli
-COPY ./target/keycloak-config-cli-*.jar .
-COPY ./docker/docker-entrypoint.bash /opt/docker-entrypoint.bash
-COPY ./docker/wtfc.sh /opt/wtfc.sh
-
-VOLUME /opt/keycloak-config-cli/configs
-
-ENTRYPOINT /opt/docker-entrypoint.bash
+ENTRYPOINT ["/bin/bash"]
